"""Generate ``virtuoso_setup.il``.

The setup file injects every remote parameter as a SKILL **global** (not a
``setShellEnvVar``), then loads ``ramic_bridge.il``.  ``ramic_bridge.il`` reads
those globals via ``unless(boundp('X) X = <fallback>)``.
"""

from __future__ import annotations


def generate_setup_il(
    daemon: str,
    il: str,
    python_cmd: str,
    port: int,
    token: str,
    identity: str | None = None,
) -> str:
    lines = [
        "; Generated by virtuoso-bridge — load this file in CIW.",
        "; All configuration is injected as SKILL globals (no shell env vars).",
        f'RBDPath = "{daemon}"',
        f'RBPython = "{python_cmd}"',
        f"RBPort = {port}",
        f'RBIdentityPath = "{identity or ""}"',
        f'RBDToken = "{token}"',
        # every load prints the token so the user can visually confirm
        # (multi-user design §3.5: confirmation is the authorization step)
        'printf("[RAMIC] token=%L\\n" RBDToken)',
        f'load("{il}")',
        "",
    ]
    return "\n".join(lines)


__all__ = ["generate_setup_il"]
